# Site settings
title: Sharp Bell
header-img: img/header_gsl2.jpg
email_username: firstname.lastname@gmail.com
copyright_name: Osvaldo Zagordi
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Osvaldo Zagordi, data scientist at University of Zurich and
  founder of enGene Statistics. Data science, statistics, science, machine
  learning, python, R and so on.
baseurl:
url: "https://ozagordi.github.io"
#twitter_username: SBootstrap
github_username: ozagordi
linkedin_username: osvaldozagordi
#facebook_username: IronSummitMedia

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: 'UA-80133486-1'

# Build settings
markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge
#highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","contact.html"]
gems:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-pandoc
pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
